language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-16
    - android-19
    - android-21
    - android-26
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - git clone https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root

env:
  matrix:
    - ANDROID_TARGET=android-16 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

script: ./gradlew clean build

sudo: true
