language: android

jdk:
- oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.0
    - android-19
    - android-21
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - echo y | sdkmanager "cmake;3.6.4111459"
  - git clone --depth 1 https://github.com/urho3d/android-ndk.git $HOME/android-ndk-root
  - export ANDROID_NDK_HOME=$HOME/android-ndk-root

# see https://github.com/travis-ci/travis-ci/issues/8874
before_install:
  - yes | sdkmanager "platforms;android-27"

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a
    - ANDROID_TARGET=android-21 ANDROID_ABI=armeabi-v7a

script: ./gradlew clean build

sudo: true